✨: Extended AzureRM Credentials
gaia-app/gaia pull request #669
Opened 2021-08-03 14:44 UTC by candidson

## Description

Added ARM_SUBSCRIPTION_ID, ARM_TENANT_ID, ARM_ACCESS_KEY and ARM_ENVIRONMENT as part of the Azure Credentials details

resolves https://github.com/gaia-app/gaia/issues/667

## Checklist for the pull request author

- [x] Tests added for this feature
- [x] Commit messages follow conventions (see [CONTRIBUTING.md](CONTRIBUTING.md))
- [x] Commits are combined ( 1 commit / type and scope )
- [x] Documentation created / updated (if necessary)
- [x] No new sonarqube issues added
- [ ] CI pipeline is OK
- [ ] Pull request is fast-forward to the `main` branch
- [ ] The last commit of this merge request :
    - [ ] updates the `pom.xml` to a new minor or major version
    - [ ] updates the `CHANGELOG.md`

## Checklist for the project maintainer

- [ ] Review the code, and add a *Review Approval* if everything is ok
- [ ] This pull request will be merged in merge-commit mode
    - (in github or with the CLI, see [CONTRIBUTING.md](CONTRIBUTING.md))

### After the merge

- [ ] Put the tag on the merged commit
    - (in github or with the CLI, see [CONTRIBUTING.md](CONTRIBUTING.md))
- [ ] Follow the pipeline for the tag, which should build & release the package (maven or docker)

## Issues / Links

* Documentation PR : (eg: gaia-app/docs#1)

(Please add issues resolution information when needed)

2021-08-03 16:23 UTC, juwit requested changes
Looks great !
Thanks a lot for this contribution !

The following tests are failing:
io.gaia_app.credentials.CredentialsRestControllerIT#users_shouldBeAbleToCreate_newAzurermCredentials
It's simply missing the new fields you added.

There's also a missing implementation in the VaultCredentialsService:
io.gaia_app.vault.VaultCredentialsServiceKt#encryptAzurermCredentials
and
io.gaia_app.vault.VaultCredentialsServiceKt#decryptAzurermCredentials
Those will correct the failing tests in VaulCredentialsServiceTest

The last failing test should pass after you accept the suggestion.

2021-08-03 16:23 UTC, juwit commented on src/test/java/io/gaia_app/credentials/CredentialsTest.kt
> +        assertThat(AzureRMCredentials("clientId", "secret", "subscriptionId", "tenantId", "backendAccessKey", "environment").toEnv())
```suggestion
        assertThat(AzureRMCredentials("clientId", "secret", "subscriptionId", "tenantId", "environment", "backendAccessKey").toEnv())
```

2021-08-03 17:04 UTC, candidson commented
Thanks a lot. I just accepted the changes.

2021-08-13 16:04 UTC, juwit commented
:wave: this was merged in #675, so closing this PR

2021-08-13 16:04 UTC, closed without merging